### ISSUE TITLE
adjust_time_to_hour_angle doesn't converge for RA=0.0

### ISSUE THREAD

**Issue by sbailey** [desihub/specsim#26]
transform.adjust_time_to_hour_angle doesn't converge for RA exactly equal to 0.0, but it does for epsilon away from that:

```
import astropy.units as u
import specsim.transform as tx
from astropy.time import Time

where = tx.observatories['KPNO']
dateobs = Time('2013-01-01 00:00:00', format='iso', location=where)
when = tx.adjust_time_to_hour_angle(dateobs, 1e-6*u.deg, 0.0*u.deg)  #- OK
when = tx.adjust_time_to_hour_angle(dateobs, 0.0*u.deg, 0.0*u.deg)  #- Fails to converge
```

RuntimeError: Reached max_iterations = 3.

**Comment by weaverba137** [comment]
This intrigued me so I ran the algorithm by hand.  For RA exactly zero, the LST *does* converge on the target hour angle (in this case also exactly zero), but from a funny direction:

```
lst = when.sidereal_time('apparent', longitude) - target_ra
lst
<Angle 23.280802014233128 hourangle>
when = when - (lst - hour_angle) * u.hour / (15 * u.deg) * sidereal
when
<Time object: scale='utc' format='iso' value=2012-12-31 00:46:57.953>
lst = when.sidereal_time('apparent', longitude) - target_ra
lst
<Angle 23.999999937338423 hourangle>
```
That angle is pretty close to zero, if you think about it!

I also checked `360 - 1e-6`, and that does appear to converge.

I'm going to guess there is something fishy about subtracting a Quantity that happens to be degrees from a Longitude (not an Angle), and that fishiness only happens when the Quantity is zero:
```
when.sidereal_time('apparent', longitude)
<Longitude 23.280802014233128 hourangle>
target_ra
<Quantity 0.0 deg>
when.sidereal_time('apparent', longitude) - target_ra
<Angle 23.999999937338423 hourangle>
```

**Comment by weaverba137** [comment]
PS, the values in that last example are not correct.  That was only to show the types of the objects.

**Comment by dkirkby** [comment]
I added a unit test for this on PR #37 and it seems to work now, probably because of PR #28.
